### ISSUE TITLE
[Feature Request] Diff'd color clashes w/ active file highlight

### ISSUE THREAD

**Issue by adamellsworth** [Pepeye/pep-syntax#1]
First of all thanks for putting this theme together; it's readable and easy on the eyes.

I have a plugin installed that highlights filenames if their content differs from HEAD (git), and the colors clash quite bad as you can see in the image attached. Note too that their icons as well as their parent directories are highlighted with the same yellow.

![screen shot 2015-04-08 at 2 00 03 pm](https://cloud.githubusercontent.com/assets/7034617/7055347/998d76ba-ddf7-11e4-8a91-ffd278f38587.png)

**Comment by Pepeye** [comment]
Thanks Adam

I will definitely look into it.

It's my first theme and based on my current terminal/iterm settings.  I
never really intended to share it but did so on a whim to see evaluate how
easy it is to publish atom packages :)

---

_Sam Aofolaju_

**Comment by Pepeye** [comment]
This has been fixed in the latest version.
